version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HTTPPORT=3000
      - DBSTRING=postgres://testuser:p!ssword2717@db:5555/tasker
    ports:
      - 3000:3000
    depends_on:
      - db
      
    
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: p!ssword2717
      POSTGRES_DB: tasker
      TZ: GMT-3
      PGTZ: GMT-3
    ports:
      - 5555:5555
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    command: -p 5555

